name: cFS Documentation and Guides

on:
  push:
  pull_request:

jobs:
  # Checks for duplicate actions. Skips push actions if there is a matching or
  # duplicate pull-request action.
  checks-for-duplicates:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["push", "workflow_dispatch", "schedule"]'

  checkout-and-cache:
    name: Custom checkout and cache for cFS documents
    needs: checks-for-duplicates
    if: ${{ needs.checks-for-duplicates.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bundle
        uses: actions/checkout@v2
        with:
          repository: nasa/cFS
          submodules: true

      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          path: cfe

      - name: Cache Source and Build
        id: cache-src-bld
        uses: actions/cache@v2
        with:
          path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/*
          key: cfs-doc-${{ github.run_number }}

  build-cfe-usersguide:
    needs: checkout-and-cache
    name: Build and deploy cFS documents
    uses: nasa/cFS/.github/workflows/build-deploy-doc.yml@main
    with:
      target: "[\"cfe-usersguide\"]"
      cache-key: cfs-doc-${{ github.run_number }}
      checkout: false
      buildpdf: ${{ github.event_name == 'push' && contains(github.ref, 'main')}}
      deploy: ${{ github.event_name == 'push' && contains(github.ref, 'main')}}

  build-mission-doc:
    needs: checkout-and-cache
    name: Build and deploy cFS documents
    #uses: nasa/cFS/.github/workflows/build-deploy-doc.yml
    uses: skliper/cFS/.github/workflows/build-deploy-doc.yml@fix447-deploy_mission_doc
    with:
      target: "[\"mission-doc\"]"
      cache-key: cfs-doc-${{ github.run_number }}
      checkout: false
      deploy: false
      buildpdf: false # No need for mission pdf within cFE, done at bundle level
